#horang.dev.ericfrom



#horang.dev.ericfrom
server {

    # 1. 수신 포트 설정 (외부 요청이 50001로 들어오므로)
    listen 50001 ssl;
    #ipv6
    listen [::]:50001 ssl;

    # 2. 도메인 설정
    server_name horang.dev.ericfromkorea.com;
    #ssl
    ssl_certificate /etc/nginx/ssl/horang/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/horang/privkey.pem;
    # 3. 로그 설정 (문제 발생 시 디버깅을 위해 추천)
    access_log /var/log/nginx/dev-eric-access.log;
    error_log /var/log/nginx/dev-eric-error.log;

    # 4. 리버스 프록시 설정
    location / {
        # 들어온 요청을 그대로 NAS의 앱으로 토스합니다.
        # 예: horang.dev.ericfromkorea.com:50001/get-all-data -> 192.168.1.129:5008/get-all-data

        proxy_pass http://localhost:5008;


        # 5. 헤더 전달 (백엔드 앱이 클라이언트의 진짜 정보를 알 수 있게 필수 설정)
        # $host: 클라이언트가 요청한 도메인 (horang.dev.ericfromkorea.com)
        proxy_set_header Host $host:$server_port;

        # $remote_addr: 클라이언트의 실제 IP
        proxy_set_header X-Real-IP $remote_addr;

        # $proxy_add_x_forwarded_for: 거쳐온 프록시 서버들의 IP 목록
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # http/https 프로토콜 정보
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
